apiVersion: k3d.io/v1alpha3
kind: Simple
name: test-gslb3
image: docker.io/rancher/k3s:v1.21.2-k3s1
agents: 1
network: k3d-action-bridge-network
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6446"
ports:
  - port: 83:80
    nodeFilters:
      - agent:0:direct
  - port: 446:443
    nodeFilters:
      - agent:0:direct
  - port: 9083:30090
    nodeFilters:
      - agent:0:direct
  - port: 5056:53/udp
    nodeFilters:
      - agent:0:direct
options:
  k3d:
    disableLoadbalancer: true
  k3s:
    extraArgs:
      - arg: --no-deploy=traefik,servicelb,metrics-server,local-storage
        nodeFilters:
          - server:*
